---
title: "Statistical Learning"
subtitle: "Introduction to Statistical Learning"
description: "Understanding the fundamentals of statistical learning."
categories:
  - statistical-learning
---

## Defining Statistical Learning


::: {.callout-tip}
This section introduces the concept of statistical learning, with a
practice example selected from the textbook. The `advertising` dataset
is located in the `data/isl/` directory.
:::

```{python}
#| label: setup
#| echo: false

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# colors
ECONOMIST_RED = "#E3120B"
ECONOMIST_RED_60 = "#F6423C"

CHICAGO_20 = "#141F52"
CHICAGO_30 = "#1F2E7A"
CHICAGO_45 = "#2E45B8"
CHICAGO_55 = "#475ED1"
CHICAGO_90 = "#D6DBF5"
CHICAGO_95 = "#EBEDFA"

HONG_KONG_45 = "#1DC9A4"
HONG_KONG_55 = "#36E2BD"
HONG_KONG_90 = "#D2F9F0"
HONG_KONG_95 = "#E9FCF8"

TOKYO_45 = "#C91D42"
TOKYO_55 = "#E2365B"
TOKYO_90 = "#F9D2DB"
TOKYO_95 = "#FCE9ED"

SINGAPORE_55 = "#F97A1F"
SINGAPORE_65 = "#FB9851"
SINGAPORE_75 = "#FCB583"
SINGAPORE_90 = "#FEE1CD"

NEW_YORK_55 = "#F9C31F"
NEW_YORK_65 = "#FBD051"
NEW_YORK_75 = "#FCDE83"
NEW_YORK_90 = "#FEF2CD"

LONDON_5 = "#0D0D0D"
LONDON_10 = "#1A1A1A"
LONDON_20 = "#333333"
LONDON_35 = "#595959"
LONDON_70 = "#B3B3B3"
LONDON_85 = "#D9D9D9"
LONDON_95 = "#F2F2F2"
LONDON_100 = "#FFFFFF"

LOS_ANGELES_85 = "#E1DFD0"
LOS_ANGELES_90 = "#EBE9E0"
LOS_ANGELES_95 = "#F5F4EF"

PARIS_85 = "#D0E1E1"
PARIS_90 = "#E0EBEB"
PARIS_95 = "#EFF5F5"
```

### Data & Problem Setup

Let us suppose that we have a dataset containing information about advertising expenditures and sales for a company. The dataset take the following form:

```{python}
#| label: load-data

# load the advertising dataset
a = pd.read_csv("../../../data/isl/advertising.csv")

# rename columns
columns_name = {
  "TV": "tv",
  "Radio": "radio",
  "Newspaper": "newspaper",
  "Sales": "sales"
}
a = a.rename(columns=columns_name)

# select relevant columns
a = a[columns_name.values()].copy()
a['idx'] = a.index

# put idx as the first column
cols = ['idx'] + [col for col in a.columns if col != 'idx']
a = a[cols]

# show first few rows of the dataset
a.head()
```

In this setting, we are interested in understanding how advertising expenditures on TV, radio, and newspapers affect sales. The goal is to build a statistical model that can predict sales based on the advertising expenditures. As such, the variable `sales` is the **response** variable, while `tv`, `radio`, and `newspaper` are the **predictor** variables.

The mathematical representation of the problem can be expressed as follows:

$$
Y = f(X_1, X_2, X_3) + \epsilon = f(X) + \epsilon
$$ {#eq-001}

where \(f\) is the unknown function that relates the predictors $X = (X_1, X_2, X_3)$ to the response $Y$, and \(\epsilon\) is the error term that captures the variability in sales not explained by the predictors (typically assumed to be normally distributed with mean zero). For instance, we could consider the following scatter plots that illustrate the relationship between each predictor and the response variable.

```{python}
#| label: scatter-plot
#| fig-cap: "Scatter plots of sales against advertising expenditures on TV, radio, and newspapers. (95% C.I.)."

# plot
fig, ax = plt.subplots(1, 3, figsize=(8, 4), sharey=True)

# lines
for i, col in enumerate(['tv', 'radio', 'newspaper']):
  sns.scatterplot(data=a, x=col, y='sales', ax=ax[i], color=ECONOMIST_RED_60, edgecolor=LONDON_20, s=50, zorder=1)
  sns.regplot(data=a, x=col, y='sales', ax=ax[i], scatter=False, color=CHICAGO_55)

  # labels
  ax[i].set_title(f'Sales vs {col.capitalize()}', fontsize=12, fontweight='bold', family='Arial Narrow', loc='left')
  ax[i].set_xlabel(f'{col.capitalize()} Expenditure', fontsize=9, fontweight='bold', family='Arial')
  ax[i].set_ylabel('Sales', fontsize=9, fontweight='bold', family='Arial')

  # aesthetics
  ax[i].spines['top'].set_visible(False)
  ax[i].spines['right'].set_visible(False)
  ax[i].tick_params(axis='both', which='major', labelsize=9)
  ax[i].grid(axis='y', linestyle='-', alpha=1, color=LONDON_85)

plt.show()
```

Apparently, for each variable $X_i \in X$, there is a positive relationship with the response variable $Y$. This suggests that as advertising expenditures increase, sales also tend to increase. However, the strength and nature of these relationships may vary.


### Why Estimate $f$?

In statistical learning, we should clearly define the goal of estimating the function $f$. We distinguish between two main reasons presented below.

#### Prediction

The primary goal is to predict the response variable $Y$ for new observations of the predictor variables $X$. In this case, we are interested in building a model that can accurately forecast sales based on advertising expenditures. The focus is on minimizing prediction error and improving the model's generalization to unseen data. We do not necessarily care about the specific form and interpretability of the function $f$, as long as it provides accurate predictions. In these settings, we denote the predicted sales as $\hat{Y}$ and the predicted function as $\hat{f}$.

Importantly, the accuracy of the prediction $Y$ with respect to the prediction $\hat Y$ depends on two quantities: (i) the *irreducible error*, and (ii) the *reducible* error.
By definition, the reducible error can be decreased by improving $\hat f$. However, since $Y$ is also a function of $\epsilon \sim \mathcal{N}(0, \sigma^2)$ and $E(\epsilon \mid X) = 0$; we cannot *perfectly* estimate $Y$ with $\hat Y$.

To illustrate this, let us consider the *fixed* set of predictors $X$ with the model $\hat Y = \hat{f}(X)$ and we further suppose that $\hat f$ is also fixed. Then, we have:

$$
\begin{aligned}
E\left[(Y-\hat{Y})^2\right]
&= E\left[\left(f(X)+\epsilon-\hat{f}(X)\right)^2\right] \\
&= E\left[
    (f(X)-\hat{f}(X))^2
    + \epsilon^2
    + 2\epsilon(f(X)-\hat{f}(X))
\right] \\
&= E\left[(f(X)-\hat{f}(X))^2\right]
   + E[\epsilon^2] \\
&=
\underbrace{(f(X)-\hat f(X))^2}_{\text{reducible error}}
+
\underbrace{\operatorname{Var}(\epsilon)}_{\text{irreducible error}}
\end{aligned}
$$

since the cross product is $0$ because $E[\epsilon (f(X) - \hat{f(X)})] = E[E[\epsilon (f(X) - \hat{f(X)}) \mid X] = 0$ by definition of the error term. The core techniques we will learn aim to estimate $f$ while minimizing the reducible error.


#### Inference

*Inference* is a completely different paradigm. It focuses on *understanding* the association between $Y$ and $X_1, \cdots, X_p$. Here, we estimate $f$ but our goal is to estimate as precisely as possible $Y$. The educated reader will notice that the science focused on developing these interpretable models is Econometrics. The types of model we select and the assumptions we formulate vary based on our goal: prediction or inference.

### How Do We Estimate $f$?

When estimating $f$, we will always assume that we used $n$ *training data* points.
I rely on the same notation as @james2023 and we let $x_{i, j}$ denotes the $j$-th predictor (among the $p$ predictors we have), or input, for observation $i$; so we have $i \in \{1, \cdots, n\}$ and $j \in \{1, \cdots, p\}$.
Correspondingly, we have $y_i$ representing the response variable for the $i$-th observation.
Now, among the different function $\hat{f}$ we can estimate, we can typically classify them as either (i) *parametric*, and (ii) *non-parametric*.

#### Parametric Methods

when we opt for a parametric approach, this means that first we select a model. For instance, a *linear model* such as:

$$
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + (\cdots) + \beta_p X_p
$$

Now, instead of having to estimate an arbitrary $p$-dimensional function, we simply need to estimate the $p + 1$ $\beta_k$ coefficients. Selecting the method to use our $n$ training instances to *fit* or *train* our model is the second step. For instance, ordinary least squares (OLS) is a closed form solution to this optimization (we try to minimize the reducible error) problem. This linear model is referred to as *parametric* because it reduces the problem of estimating $f$ to estimating $p$ parameters.
Of course, if we select a model whose form is far off from the *true* $f$, we will obtain poor results. We could then increase the flexibility of our model but we expose ourselves to *overfitting* the training data, i.e. our model fits very well the $n$ training instances but generalize very poorly to unseen data.

#### Non-Parametric Methods

For non-parametric methods, no assumption about the form of $f$ is made, so the risk of selecting a faulty functional form is gone.
However, typically, since we do not *reduce* our optimization problem, the number of training instances needed to obtain a precise estimation of $f$ is much larger.
Splines, discussed further in this summary, are an example of non-parametric methods.


### Supervised Versus Unsupervised Learning

TO BE WRITTEN (small overview and dicussion, one visual example with generated data for clustering)

### Regression Versus Classification

TO BE WRITTEN

## Assessing Model Accuracy

Selecting the best approach can be one of the most challenging parts of performing statistical learning in
practice because for any given dataset, we might have a different *optimal* technique to estimate $f$. Furthermore,
how do we determine which approach is the *best* for a given problem? This section explores this question.

### Measuring the Quality of Fit

Measuring the quality of the fit, i.e. how well our estimated function $\hat{f}$ predicts $Y$, depends on the type of task we are tackling.
In the regression settings, the most commonly-used measure is the *mean-squared error* (MSE), given by:

$$
\text{MSE} = \frac{1}{n} \sum_{i = 1}^{n} (y_i - \hat{f}(x_i))^2
$$

where $\hat{f}(x_i) = \hat y_i$ is the prediction given by $\hat f$ for the $i$-th observation.
Typically, when training our model (used for a regression task) we seek to minimize the MSE; however,
we are measuring the MSE with our *training* data, hence the *training MSE* is not to be understood as a reliable metric
of our model's accuracy. To get that, we should use our model to predict unseen *test data*. Then the MSE will be more
informative and tells us how our model *really* perform. For instance, if we observe $MSE_{\text{test}} \gg MSE_{\text{training}}$,
this suggests that our model is overfitting the training data. Below, I generate a synthetic example to illustrate this.


#### Overfitting Training Data: A Synthetic Example

Let us consider a plausible regresssion problem whith one regressor variable $X$, representing the size of a flat in square meters, and $Y$ being the monthly rent in CHF. We build a model to create these data. Below is a snapshot of the resulting dataframe.

```{python}
# generate the data with the following model:
# model: y = a + bX + e
# (y: rent in CHF, x: flat size in square meters, e: error term / noise)
# > X ~ N(80, 20^2)
# > e ~ N(0, 300^2)
# > a = 300, b = 25

# fix the seed for reproducibility
np.random.seed(1)

# parameters
a = 300
b = 25
X_std = 20
X_mean = 80
e_std = 300
e_mean = 0

# size of the whole sample
N = 1000

# test and train sample sizes
n_train = int(0.8 * N)
n_test = 0.2 * N

# draw data for X and e
X = np.random.normal(loc=X_mean, scale=20, size=N)
e = np.random.normal(loc=e_mean, scale=e_std, size=N)

# compute Y
Y = a + b * X + e

# data frame for whole sample
sample = pd.DataFrame(
  {
    "size": X,
    "rent": Y
  }
)

# split test and train set
df_train = sample.iloc[:n_train].copy().reset_index(drop=True)
df_test = sample.iloc[n_train:].copy().reset_index(drop=True)

# head of the dataset
df_train.head()
```

